{{ if .Values.schedule.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "capacity-reservation.fullname" . }}-down
spec:
  schedule: {{ .Values.schedule.down.cron | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "capacity-reservation.schedule.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "capacity-reservation.serviceAccountName" . }}
          containers:
          - name: schedule
            image: {{ .Values.schedule.image }}
            imagePullPolicy: {{ .Values.schedule.imagePullPolicy }}
            command:
              - /bin/sh
              - -c
              - kubectl scale --replicas={{ .Values.schedule.down.reservation.replicas }} deployment/{{ include "capacity-reservation.fullname" . }}-reservation --namespace {{ .Release.Namespace }}
            resources:
              {{- toYaml .Values.schedule.down.resources | nindent 14 }}
          restartPolicy: OnFailure
          {{- with .Values.schedule.nodeSelector }}
          nodeSelector:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.schedule.affinity }}
          affinity:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.schedule.tolerations }}
          tolerations:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.schedule.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
{{- end }}
