apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "capacity-reservation.fullname" . }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list","patch"]
