# -- Reservation deployment configuration
reservation:
  # -- Whether reservation is enabled
  enabled: true
  # -- Each replica reserves one node
  replicas: 1
  # -- Reservation image configuration
  image: registry.k8s.io/pause:latest
  imagePullPolicy: Always
  affinity: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "capacity-reservation.reservation.selectorLabels" . | nindent 12 }}
            topologyKey: topology.kubernetes.io/zone
          weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "capacity-reservation.reservation.selectorLabels" . | nindent 10 }}
          topologyKey: kubernetes.io/hostname

schedule:
  enabled: false
  up:
    cron: "0 8 * * 1-5"
    reservation:
      replicas: 1
  down:
    cron: "0 17 * * 1-5"
    reservation:
      replicas: 0
  image: bitnami/kubectl:latest
  # -- Schedule image imagePullPolicy
  imagePullPolicy: Always
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
  # -- Number of successful Jobs to keep
  successfulJobsHistoryLimit: 1
  # -- Number of failed Jobs to keep
  failedJobsHistoryLimit: 1
  # -- Concurrency policy https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#concurrency-policy
  concurrencyPolicy: Replace
  # -- Set to true to suspend the CronJob
  suspend: false

# -- Service Account, ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # -- Specifies whether a ServiceAccount should be created
  create: true
  # -- Annotations for service account. Evaluated as a template. Only used if `create` is `true`.
  annotations: {}
  # -- Name of the service account to use. If not set and create is true, a name is generated using the fullname template.
  name: ""
